import { translateCreditScore } from "@/lib/credit-engine";
import type {
  DemoConsumer,
  LenderApplicationRow,
  TimelineEntry,
} from "@/lib/types";

export const DEMO_IDS = {
  consumers: {
    priya: "11111111-1111-4111-8111-111111111111",
    james: "22222222-2222-4222-8222-222222222222",
    carlos: "33333333-3333-4333-8333-333333333333",
    emma: "44444444-4444-4444-8444-444444444444",
    aisha: "55555555-5555-4555-8555-555555555555",
  },
  profiles: {
    priya: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
    james: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
    carlos: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
    emma: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4",
    aisha: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5",
  },
  lenders: {
    community: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1",
    apex: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2",
  },
} as const;

const now = new Date().toISOString();

const timelineTemplate = (
  consumerId: string,
  seed: number,
): TimelineEntry[] => [
  {
    id: `${consumerId}-cc-1`,
    accountType: "Credit Card",
    institution: "GlobalBank Platinum",
    openedDate: "2019-05-01",
    closedDate: null,
    creditLimit: 8000 + seed * 100,
    balance: 2300 + seed * 50,
    status: "Active",
    paymentHistory: ["on_time", "on_time", "on_time", "late", "on_time"],
  },
  {
    id: `${consumerId}-cc-2`,
    accountType: "Credit Card",
    institution: "Cityline Rewards",
    openedDate: "2020-11-01",
    closedDate: null,
    creditLimit: 5000 + seed * 120,
    balance: 800 + seed * 40,
    status: "Active",
    paymentHistory: ["on_time", "on_time", "on_time", "on_time", "on_time"],
  },
  {
    id: `${consumerId}-pl-1`,
    accountType: "Personal Loan",
    institution: "Trust Lending",
    openedDate: "2018-03-01",
    closedDate: "2021-03-01",
    creditLimit: 12000,
    balance: 0,
    status: "Closed",
    paymentHistory: ["on_time", "on_time", "on_time", "on_time", "on_time"],
  },
  {
    id: `${consumerId}-pl-2`,
    accountType: "Personal Loan",
    institution: "Metro Loan Co.",
    openedDate: "2022-08-01",
    closedDate: null,
    creditLimit: 7000,
    balance: 1400,
    status: "Active",
    paymentHistory: ["on_time", "late", "on_time", "on_time", "on_time"],
  },
  {
    id: `${consumerId}-auto-1`,
    accountType: "Auto Loan",
    institution: "Velocity Auto Finance",
    openedDate: "2021-01-01",
    closedDate: null,
    creditLimit: 18000,
    balance: 7200,
    status: "Active",
    paymentHistory: ["on_time", "on_time", "on_time", "on_time", "on_time"],
  },
  {
    id: `${consumerId}-mortgage-1`,
    accountType: "Mortgage",
    institution: "Homestead Mortgage",
    openedDate: "2017-06-01",
    closedDate: null,
    creditLimit: 220000,
    balance: 187000,
    status: seed % 2 === 0 ? "Active" : "Delinquent",
    paymentHistory:
      seed % 2 === 0
        ? ["on_time", "on_time", "on_time", "on_time", "on_time"]
        : ["on_time", "late", "missed", "on_time", "late"],
  },
  {
    id: `${consumerId}-utility-1`,
    accountType: "Utility",
    institution: "National Power",
    openedDate: "2016-02-01",
    closedDate: null,
    creditLimit: 2000,
    balance: 120,
    status: "Active",
    paymentHistory: ["on_time", "on_time", "on_time", "on_time", "on_time"],
  },
  {
    id: `${consumerId}-utility-2`,
    accountType: "Utility",
    institution: "Urban Water",
    openedDate: "2016-02-01",
    closedDate: null,
    creditLimit: 1200,
    balance: 85,
    status: "Active",
    paymentHistory: ["on_time", "on_time", "on_time", "on_time", "on_time"],
  },
];

function buildConsumer(
  id: string,
  profileId: string,
  fullName: string,
  email: string,
  countryCode: "IN" | "GB" | "MX" | "AU" | "CA",
  countryName: string,
  bureauName: string,
  foreignScore: number,
  foreignMax: number,
  seed: number,
): DemoConsumer {
  const translated = translateCreditScore(foreignScore, countryCode, foreignMax);

  return {
    id,
    email,
    fullName,
    profile: {
      id: profileId,
      userId: id,
      userName: fullName,
      homeCountryCode: countryCode,
      homeCountryName: countryName,
      bureauName,
      foreignScore,
      foreignScoreMax: foreignMax,
      translatedScore: translated.translatedScore,
      riskTier: translated.riskTier,
      status: "complete",
      scoreBreakdown: translated.scoreBreakdown,
      flags: translated.flags,
      recommendation: translated.recommendation,
      creditAgeMonths: 24 + seed * 12,
      lastUpdatedAt: now,
    },
    timeline: timelineTemplate(id, seed),
  };
}

export const DEMO_CONSUMERS: DemoConsumer[] = [
  buildConsumer(
    DEMO_IDS.consumers.priya,
    DEMO_IDS.profiles.priya,
    "Priya Sharma",
    "priya@demo.com",
    "IN",
    "India",
    "CIBIL",
    780,
    900,
    1,
  ),
  buildConsumer(
    DEMO_IDS.consumers.james,
    DEMO_IDS.profiles.james,
    "James Mitchell",
    "james@demo.com",
    "GB",
    "United Kingdom",
    "Experian UK",
    887,
    999,
    2,
  ),
  buildConsumer(
    DEMO_IDS.consumers.carlos,
    DEMO_IDS.profiles.carlos,
    "Carlos Mendoza",
    "carlos@demo.com",
    "MX",
    "Mexico",
    "Buro de Credito",
    660,
    850,
    3,
  ),
  buildConsumer(
    DEMO_IDS.consumers.emma,
    DEMO_IDS.profiles.emma,
    "Emma Wilson",
    "emma@demo.com",
    "AU",
    "Australia",
    "Equifax Australia",
    750,
    1200,
    4,
  ),
  buildConsumer(
    DEMO_IDS.consumers.aisha,
    DEMO_IDS.profiles.aisha,
    "Aisha Nkrumah",
    "aisha@demo.com",
    "CA",
    "Canada",
    "Equifax Canada",
    745,
    900,
    5,
  ),
];

function maskName(fullName: string) {
  const [first = "", last = ""] = fullName.split(" ");
  return `${first} ${last.slice(0, 1)}.`;
}

export const DEMO_LENDERS = [
  {
    id: DEMO_IDS.lenders.community,
    name: "Community First Credit Union",
    email: "community@demo.com",
    webhookUrl: "https://example.com/community-first/webhook",
    apiCallsThisMonth: 1245,
    approvalRate: 68,
    avgDecisionHours: 19,
  },
  {
    id: DEMO_IDS.lenders.apex,
    name: "Apex Mortgage Group",
    email: "apex@demo.com",
    webhookUrl: "https://example.com/apex/webhook",
    apiCallsThisMonth: 842,
    approvalRate: 53,
    avgDecisionHours: 31,
  },
];

export const DEMO_APPLICATIONS: LenderApplicationRow[] = [
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc1",
    lenderId: DEMO_IDS.lenders.community,
    lenderName: "Community First Credit Union",
    profileId: DEMO_IDS.profiles.priya,
    consumerNameMasked: maskName("Priya Sharma"),
    countryCode: "IN",
    score: 700,
    riskTier: "good",
    status: "approved",
    submittedAt: "2026-03-01T09:30:00.000Z",
    decisionAt: "2026-03-02T08:20:00.000Z",
    lenderNotes: "Strong repayment record.",
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc2",
    lenderId: DEMO_IDS.lenders.community,
    lenderName: "Community First Credit Union",
    profileId: DEMO_IDS.profiles.carlos,
    consumerNameMasked: maskName("Carlos Mendoza"),
    countryCode: "MX",
    score: 589,
    riskTier: "fair",
    status: "under_review",
    submittedAt: "2026-03-04T13:00:00.000Z",
    decisionAt: null,
    lenderNotes: "Need additional income verification.",
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc3",
    lenderId: DEMO_IDS.lenders.community,
    lenderName: "Community First Credit Union",
    profileId: DEMO_IDS.profiles.aisha,
    consumerNameMasked: maskName("Aisha Nkrumah"),
    countryCode: "CA",
    score: 708,
    riskTier: "good",
    status: "submitted",
    submittedAt: "2026-03-08T11:10:00.000Z",
    decisionAt: null,
    lenderNotes: null,
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc4",
    lenderId: DEMO_IDS.lenders.apex,
    lenderName: "Apex Mortgage Group",
    profileId: DEMO_IDS.profiles.james,
    consumerNameMasked: maskName("James Mitchell"),
    countryCode: "GB",
    score: 788,
    riskTier: "excellent",
    status: "approved",
    submittedAt: "2026-02-18T10:00:00.000Z",
    decisionAt: "2026-02-19T15:30:00.000Z",
    lenderNotes: "Approved under prime policy.",
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-ccccccccccc5",
    lenderId: DEMO_IDS.lenders.apex,
    lenderName: "Apex Mortgage Group",
    profileId: DEMO_IDS.profiles.emma,
    consumerNameMasked: maskName("Emma Wilson"),
    countryCode: "AU",
    score: 644,
    riskTier: "fair",
    status: "denied",
    submittedAt: "2026-03-10T09:00:00.000Z",
    decisionAt: "2026-03-10T17:00:00.000Z",
    lenderNotes: "Score below minimum threshold of 660",
  },
];

export const DEMO_DOCUMENTS = DEMO_CONSUMERS.flatMap((consumer) => [
  {
    id: `dddddddd-dddd-4ddd-8ddd-${consumer.id.slice(-12)}`,
    user_id: consumer.id,
    profile_id: consumer.profile.id,
    name: "Foreign Credit Report",
    doc_type: "credit_report",
    status: "verified",
    uploaded_at: "2026-03-01T12:00:00.000Z",
  },
  {
    id: `eeeeeeee-eeee-4eee-8eee-${consumer.id.slice(-12)}`,
    user_id: consumer.id,
    profile_id: consumer.profile.id,
    name: "Passport",
    doc_type: "passport",
    status: "verified",
    uploaded_at: "2026-03-01T12:05:00.000Z",
  },
]);

export const DEMO_API_USAGE = Array.from({ length: 30 }).map((_, index) => ({
  day: `${index + 1}`,
  calls: Math.max(22, Math.round(45 + Math.sin(index / 4) * 35 + index)),
}));
